// autogenerated from foo.json
// Mon Jul 22 02:32:01 2019

#ifndef _SYNTH_H
#define _SYNTH_H

/* Number of float (32 bit) samples synth can safely generate without
   internal overflow, i.e. max safe value for 2nd arg of synth().
   That arg divided by 2 is the number of interleaved stereo frames generated. */

#define SONG_FRAMES (26 * 21000 * 15)

#ifdef __cplusplus
extern "C" {
#endif

__attribute__((regparm(2))) void synth(float *outbuf, int samples);

#ifdef __cplusplus
}
#endif

#endif /* _SYNTH_H */
